config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  resources :users, only: [:index, :show]
  
  resources :products do
    get :who_bought, on: :member
  end
  
  scope '(:locale)' do
    devise_for :users, path: 'u'
    resources :orders
    resources :line_items
    resources :carts
    resources :categories
    get 'store/refresh_cart'
    root 'store#index', as: 'store', via: :all
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input).hide()" %>
    <% end %>
		<%= image_tag("logo.png") %>
		<%= @page_title || t('.title') %>
	</div>
	<div id="columns">
		<div id="side">
			<ul>
				<li><%= link_to t('.home'), store_path %></li><br/>
        
        <% if user_signed_in? %>
          <div id="text">
            <%= "Signed in as #{current_user.name}" %>
            <br/>
            <%= button_to('Logout', destroy_user_session_path, :method => :delete) %>        
          
          </div>
        <% else %>
          <li>
            <%= button_to('Login', new_user_session_path, method: :get)  %>  
          </li>
        <% end %>
        <br/>
        <% if user_signed_in? %>
        <br>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
        <li><%= link_to "Orders", orders_path %></li>
        <% end %>
				<br>
			</ul>
			
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>

        
      
      <br />
      <br />
      <li id="time">Page accessed at <%= Time.now %></li>
      
		</div>
		<div id="main">
			<%= yield %>
		</div>
</div>
</body>
</html>